### ISSUE TITLE
m2o error in Odoo 8.0

### ISSUE THREAD

**Issue by rvalyi** [akretion/ooor#117]
why the hell the array of ids to read that is passed is [false]

```
irb(main):004:0> m=StockMove.find(62)
irb(main):004:0> m.associations["move_dest_id"]
[61, "RAM-SR2: Fabrica > Production"]
irb(main):005:0> m.move_dest_id
D, [2014-09-18T04:02:31.619925 #25933] DEBUG -- : OOOR object service: rpc_method: execute, db: db, uid: 1, pass: #, obj: stock.move, method: read, *args: [[false], ["origin", "product_uos_qty", "create_date", "weight", "price_unit", "product_uom_qty", "date", "product_qty", "availability", "remaining_qty", "note", "display_name", "id", "priority", "state", "date_expected", "name", "string_availability_info", "weight_net", "partially_available", "propagate", "procure_method", "scrapped", "__last_update", "invoice_state", "reserved_availability", "write_date", "quant_ids", "route_ids", "lot_ids", "move_orig_ids", "linked_move_operation_ids", "returned_move_ids", "reserved_quant_ids", "move_dest_id", "company_id", "product_uos", "location_id", "product_uom", "consumed_for", "picking_type_id", "partner_id", "picking_id", "origin_returned_move_id", "product_packaging", "purchase_line_id", "raw_material_production_id", "procurement_id", "backorder_id", "create_uid", "warehouse_id", "inventory_id", "restrict_partner_id", "write_uid", "restrict_lot_id", "group_id", "split_from", "weight_uom_id", "location_dest_id", "production_id", "push_rule_id", "product_id", "rule_id"], {}]
Ooor::OpenERPServerError: 

********************************************
***********     OOOR Request     ***********
method: read - args: [[false], ["origin", "product_uos_qty", "create_date", "weight", "price_unit", "product_uom_qty", "date", "product_qty", "availability", "remaining_qty", "note", "display_name", "id", "priority", "state", "date_expected", "name", "string_availability_info", "weight_net", "partially_available", "propagate", "procure_method", "scrapped", "__last_update", "invoice_state", "reserved_availability", "write_date", "quant_ids", "route_ids", "lot_ids", "move_orig_ids", "linked_move_operation_ids", "returned_move_ids", "reserved_quant_ids", "move_dest_id", "company_id", "product_uos", "location_id", "product_uom", "consumed_for", "picking_type_id", "partner_id", "picking_id", "origin_returned_move_id", "product_packaging", "purchase_line_id", "raw_material_production_id", "procurement_id", "backorder_id", "create_uid", "warehouse_id", "inventory_id", "restrict_partner_id", "write_uid", "restrict_lot_id", "group_id", "split_from", "weight_uom_id", "location_dest_id", "production_id", "push_rule_id", "product_id", "rule_id"], {}]
********************************************


********************************************
*********** OpenERP Server ERROR ***********
********************************************
Traceback (most recent call last):
  File "/.devstep/addons/voodoo/odoo/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.devstep/addons/voodoo/odoo/openerp/http.py", line 516, in dispatch
    result = self._call_function(**self.params)
  File "/.devstep/addons/voodoo/odoo/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.devstep/addons/voodoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.devstep/addons/voodoo/odoo/openerp/http.py", line 279, in checked_call
    return self.endpoint(*a, **kw)
  File "/.devstep/addons/voodoo/odoo/openerp/http.py", line 732, in __call__
    return self.method(*args, **kw)
  File "/.devstep/addons/voodoo/odoo/openerp/http.py", line 375, in response_wrap
    response = f(*args, **kw)
  File "/workspace/parts/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/workspace/parts/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/.devstep/addons/voodoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/.devstep/addons/voodoo/odoo/openerp/models.py", line 3095, in read
    result = BaseModel.read(records, fields, load=load)
  File "/.devstep/addons/voodoo/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/.devstep/addons/voodoo/odoo/openerp/models.py", line 3138, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/.devstep/addons/voodoo/odoo/openerp/models.py", line 5441, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/.devstep/addons/voodoo/odoo/openerp/fields.py", line 704, in __get__
    return record._cache[self]
  File "/.devstep/addons/voodoo/odoo/openerp/models.py", line 5775, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/.devstep/addons/voodoo/odoo/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', 'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: stock.move, Operation: read)')

OpenERP Server Error
********************************************
.
	from /home/rvalyi/DEV/ooor/lib/ooor/transport/json_client.rb:44:in `oe_request'
	from /home/rvalyi/DEV/ooor/lib/ooor/transport/json_client.rb:24:in `oe_service'
	from /home/rvalyi/DEV/ooor/lib/ooor/services.rb:99:in `object_service'
	from /home/rvalyi/DEV/ooor/lib/ooor/base.rb:47:in `object_service'
	from /home/rvalyi/DEV/ooor/lib/ooor/base.rb:87:in `rpc_execute'
	from /home/rvalyi/DEV/ooor/lib/ooor/field_methods.rb:122:in `lazy_load'
	from /home/rvalyi/DEV/ooor/lib/ooor/field_methods.rb:128:in `get_attribute'
	from /home/rvalyi/DEV/ooor/lib/ooor/field_methods.rb:56:in `block in define_field_method'
	from /home/rvalyi/.rvm/gems/ruby-2.1.1/gems/activemodel-3.2.18/lib/active_model/dirty.rb:154:in `attribute_will_change!'
	from /home/rvalyi/.rvm/gems/ruby-2.1.1/gems/activemodel-3.2.18/lib/active_model/attribute_methods.rb:345:in `id_will_change!'
	from /home/rvalyi/DEV/ooor/lib/ooor/field_methods.rb:143:in `set_attribute'
	from /home/rvalyi/DEV/ooor/lib/ooor/field_methods.rb:60:in `block in define_field_method'
	from /home/rvalyi/DEV/ooor/lib/ooor/persistence.rb:93:in `block in load'
	from /home/rvalyi/DEV/ooor/lib/ooor/persistence.rb:92:in `each'
	from /home/rvalyi/DEV/ooor/lib/ooor/persistence.rb:92:in `load'
	from /home/rvalyi/DEV/ooor/lib/ooor/persistence.rb:107:in `initialize'
	from /home/rvalyi/DEV/ooor/lib/ooor/associations.rb:64:in `new'
	from /home/rvalyi/DEV/ooor/lib/ooor/associations.rb:64:in `load_m2o_association'
	from /home/rvalyi/DEV/ooor/lib/ooor/associations.rb:31:in `relationnal_result'
	from /home/rvalyi/DEV/ooor/lib/ooor/field_methods.rb:153:in `get_association'
	from /home/rvalyi/DEV/ooor/lib/ooor/field_methods.rb:67:in `block in define_association_method'
	from (irb):5
	from /home/rvalyi/DEV/ooor/bin/ooor:58:in `<top (required)>'
	from /home/rvalyi/.rvm/gems/ruby-2.1.1/bin/ooor:23:in `load'
	from /home/rvalyi/.rvm/gems/ruby-2.1.1/bin/ooor:23:in `<main>'
	from /home/rvalyi/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/rvalyi/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'irb(main):006:0> 

```

**Comment by jaakkoko** [comment]
Any workaround for this?
I'm getting the same error on every m2o field in Odoo v.8.0

**Comment by hugosantosred** [comment]
This error is because lazy load use in odoo v8.0 m2o associations.

I think that the problem is in args provided to this method lazy_load because id variable is nil in that case. So when rpc_execute('read', [id]...) is called openerp raises that error because is trying to read a record with id false. I don't know why is not propagating id value through methods.

As a workaround is possible to disable the lazy load in m2o fields as in this commit:

https://github.com/hugosantosred/ooor/commit/d633324aaddd2f0748054c12a4c5ea82c51007f5

**Comment by rvalyi** [comment]
not sure when I fixed this but I fixed it now.
