### ISSUE TITLE
Impossible to update ProductCategory

### ISSUE THREAD

**Issue by YannickB** [akretion/ooor#78]
Hi,

If we try to update a product.category, it throw the following error :

**********\* OpenERP Server ERROR ***********
multiple assignments to same column "write_date"

Traceback (most recent call last):
  File "/home/openerp_user/openerp/destock_prod/server/bin/netsvc.py", line 489, in dispatch
    result = ExportService.getService(service_name).dispatch(method, auth, params)
  File "/home/openerp_user/openerp/destock_prod/server/bin/service/web_services.py", line 599, in dispatch
    res = fn(db, uid, _params)
  File "/home/openerp_user/openerp/destock_prod/server/bin/osv/osv.py", line 122, in wrapper
    return f(self, dbname, *args, *_kwargs)
  File "/home/openerp_user/openerp/destock_prod/server/bin/osv/osv.py", line 176, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/openerp_user/openerp/destock_prod/server/bin/osv/osv.py", line 167, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/openerp_user/openerp/destock_prod/server/bin/addons/magentoerpconnect/product.py", line 101, in write
    return super(product_category, self).write(cr, uid, ids, vals, context)
  File "/home/openerp_user/openerp/destock_prod/server/bin/osv/orm.py", line 3410, in write
    'where id IN %s', upd1 + [sub_ids])
  File "/home/openerp_user/openerp/destock_prod/server/bin/sql_db.py", line 78, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/openerp_user/openerp/destock_prod/server/bin/sql_db.py", line 131, in execute
    res = self._obj.execute(query, params)
ProgrammingError: multiple assignments to same column "write_date"

---

Create a product.category work correctly. Also this don't happen with any other object, tested with res.partner and res.partner.category.

**Comment by rvalyi** [comment]
These Odoo "magic columns" are now properly filtered since a few years ago:
https://github.com/akretion/ooor/blob/master/lib/ooor/type_casting.rb#L11
So closing the report.
